/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JInternalFrameStudent.java
 *
 * Created on Oct 18, 2016, 8:00:48 PM
 */
package StudentProfileDetails;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author CHRISTOPHER
 */
public class JInternalFrameStudent extends javax.swing.JInternalFrame implements MouseListener {

    private Student student = new Student();

    /** Creates new form JInternalFrameStudent */
    public JInternalFrameStudent() {
        initComponents();
        setStudentTable();
        selectAllStudent();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jTextFieldUsername = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextFieldFirstname = new javax.swing.JTextField();
        jTextFieldLastname = new javax.swing.JTextField();
        jTextFieldAge = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldMobile = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(0, 2, 2, 0));

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setLayout(new java.awt.GridLayout(6, 0));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(christopher_quilaton_student_profile.Christopher_Quilaton_Student_ProfileApp.class).getContext().getResourceMap(JInternalFrameStudent.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel7.add(jLabel1);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel7.add(jLabel2);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel7.add(jLabel3);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel7.add(jLabel4);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel7.add(jLabel5);

        jPanel6.add(jPanel7, java.awt.BorderLayout.LINE_START);

        jPanel8.setName("jPanel8"); // NOI18N
        jPanel8.setLayout(new java.awt.GridLayout(6, 0));

        jTextFieldUsername.setName("jTextFieldUsername"); // NOI18N
        jPanel8.add(jTextFieldUsername);

        jPasswordField1.setText(resourceMap.getString("jPasswordField1.text")); // NOI18N
        jPasswordField1.setName("jPasswordField1"); // NOI18N
        jPanel8.add(jPasswordField1);

        jTextFieldFirstname.setName("jTextFieldFirstname"); // NOI18N
        jPanel8.add(jTextFieldFirstname);

        jTextFieldLastname.setName("jTextFieldLastname"); // NOI18N
        jPanel8.add(jTextFieldLastname);

        jTextFieldAge.setName("jTextFieldAge"); // NOI18N
        jPanel8.add(jTextFieldAge);

        jPanel6.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel9.setName("jPanel9"); // NOI18N
        jPanel9.setLayout(new java.awt.GridLayout(6, 0));

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel9.add(jLabel6);

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel9.add(jLabel7);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jPanel9.add(jLabel8);

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        jPanel9.add(jLabel9);

        jPanel5.add(jPanel9, java.awt.BorderLayout.LINE_START);

        jPanel10.setName("jPanel10"); // NOI18N
        jPanel10.setLayout(new java.awt.GridLayout(6, 0));

        jPanel12.setName("jPanel12"); // NOI18N
        jPanel12.setLayout(new java.awt.GridLayout(0, 2));

        jRadioButtonMale.setText(resourceMap.getString("jRadioButtonMale.text")); // NOI18N
        jRadioButtonMale.setName("jRadioButtonMale"); // NOI18N
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });
        jPanel12.add(jRadioButtonMale);

        jRadioButtonFemale.setText(resourceMap.getString("jRadioButtonFemale.text")); // NOI18N
        jRadioButtonFemale.setName("jRadioButtonFemale"); // NOI18N
        jRadioButtonFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFemaleActionPerformed(evt);
            }
        });
        jPanel12.add(jRadioButtonFemale);

        jPanel10.add(jPanel12);

        jTextFieldAddress.setName("jTextFieldAddress"); // NOI18N
        jPanel10.add(jTextFieldAddress);

        jTextFieldEmail.setName("jTextFieldEmail"); // NOI18N
        jPanel10.add(jTextFieldEmail);

        jTextFieldMobile.setName("jTextFieldMobile"); // NOI18N
        jPanel10.add(jTextFieldMobile);

        jPanel5.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel1.add(jPanel2);

        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableStudent.setName("jTableStudent"); // NOI18N
        jTableStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableStudent);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setName("jButton3"); // NOI18N
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButtonSave.setText(resourceMap.getString("jButtonSave.text")); // NOI18N
        jButtonSave.setFocusable(false);
        jButtonSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSave.setName("jButtonSave"); // NOI18N
        jButtonSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonSave);

        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setName("jButton4"); // NOI18N
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        if (jRadioButtonMale.isSelected()) {
            jRadioButtonFemale.setSelected(false);
        } else if (jRadioButtonFemale.isSelected()) {
            jRadioButtonMale.setSelected(false);
        }
}//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void jRadioButtonFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemaleActionPerformed
        if (jRadioButtonFemale.isSelected()) {
            jRadioButtonMale.setSelected(false);
        } else if (jRadioButtonMale.isSelected()) {
            jRadioButtonFemale.setSelected(false);
        }
}//GEN-LAST:event_jRadioButtonFemaleActionPerformed

    private void jTableStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStudentMouseClicked
}//GEN-LAST:event_jTableStudentMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
}//GEN-LAST:event_jScrollPane1MouseClicked

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
       try{
           insertStudent();
           JOptionPane.showMessageDialog(null,"Successfully Saved!");
       }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
}//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    newData();
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try{
           updateStudent();
            JOptionPane.showMessageDialog(null,"Successfully Updated!");
       }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
      
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStudent;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstname;
    private javax.swing.JTextField jTextFieldLastname;
    private javax.swing.JTextField jTextFieldMobile;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
   public void insertStudent(){

        student.setUsername(jTextFieldUsername.getText().trim());
        student.setPassword(jPasswordField1.getText().trim());
        student.setFirstname(jTextFieldFirstname.getText().trim());
        student.setLastname(jTextFieldLastname.getText().trim());
        int num = Integer.parseInt(jTextFieldAge.getText());
         if (jRadioButtonMale.isSelected()) {
            student.setGender(true);
        } else if (jRadioButtonFemale.isSelected()) {
            student.setGender(false);
        }
        student.setAge(num);
        student.setAddress(jTextFieldAddress.getText().trim());
        student.setEmail(jTextFieldEmail.getText().trim());
        student.setMobile(jTextFieldMobile.getText().trim());
        student.setDeleted(false);
        student.add();
       selectAllStudent();

}

    private void newData() {

student.setId(0);
        jTextFieldUsername.setText("");
      jPasswordField1.setText("");
        jTextFieldFirstname.setText("");
        jTextFieldLastname.setText("");
        jTextFieldAge.setText("");
        jRadioButtonMale.setSelected(true);
        jRadioButtonFemale.setSelected(false);
        jTextFieldAddress.setText("");
        jTextFieldEmail.setText("");
        jTextFieldMobile.setText("");
 selectAllStudent();
        
    }
     public void updateStudent(){

        student.setUsername(jTextFieldUsername.getText().trim());
        student.setPassword(jPasswordField1.getText().trim());
        student.setFirstname(jTextFieldFirstname.getText().trim());
        student.setLastname(jTextFieldLastname.getText().trim());
        int num = Integer.parseInt(jTextFieldAge.getText());
        if (jRadioButtonMale.isSelected()) {
            student.setGender(true);
        } else if (jRadioButtonFemale.isSelected()) {
            student.setGender(false);
        }
        student.setAge(num);
        student.setAddress(jTextFieldAddress.getText().trim());
        student.setEmail(jTextFieldEmail.getText().trim());
        student.setMobile(jTextFieldMobile.getText().trim());

        student.setDeleted(false);
        student.update();
        selectAllStudent();
    }

    public void deleteStudent() {
        student.setDeleted(true);
        student.updateDelete();
        selectAllStudent();
}
    private void selectAllStudent() {
        studentTable.setRowCount(0);
        student.select();
        for (int i = 0; i < student.getData().size(); i++) {
            studentTable.addRow((Vector) student.getData().get(i));
        }
    }
DefaultTableModel studentTable = new DefaultTableModel() {

        public Class getColumnClass(int columnIndex) {
            if (columnIndex == 6 || columnIndex == 11) {
                return Boolean.class;
            } else {
                return Object.class;
            }
        }
        //Note that the data/cell address is constant,
        //no matter where the cell appears onscreen.

        public boolean isCellEditable(int row, int col) {
            if (col < 11) {
                return false;
            } else {
                return true;
            }
        }
    }; //end of Instantiation

private TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(studentTable);

private void setStudentTable() {
        //
        String[] columnNames = {
            "id",
            "Username",
            "Password",
            "Firstname",
            "Lastname",
            "Age",
            "Gender",
            "Address",
            "EmailAdd",
            "Mobile1",
            "Mobile2",
           // "Deleted"
           };
        jTableStudent = new javax.swing.JTable(studentTable);
        jTableStudent.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableStudent.setShowGrid(false);
        jTableStudent.setFillsViewportHeight(true);
        jTableStudent.getTableHeader().setReorderingAllowed(false);
        jTableStudent.addMouseListener(this);
        jTableStudent.setColumnSelectionAllowed(true);
        jTableStudent.setAutoCreateRowSorter(true);
        jTableStudent.setRowSorter(sorter);
        jScrollPane1.setViewportView(jTableStudent);
        JTableHeader header =jTableStudent.getTableHeader();
        header.setBackground(Color.ORANGE);
        //...set columnNames in table columns
        for (int i = 0; i < columnNames.length;) {
            studentTable.addColumn(columnNames[i]);
            i++;
        }

        TableColumn[] column = new TableColumn[100];
        //...
        column[0] = jTableStudent.getColumnModel().getColumn(0);
        column[0].setPreferredWidth(50);

        column[1] = jTableStudent.getColumnModel().getColumn(1);
        column[1].setPreferredWidth(80);

        column[2] = jTableStudent.getColumnModel().getColumn(2);
        column[2].setPreferredWidth(100);

        TableColumn hidden1 = jTableStudent.getColumnModel().getColumn(0);
        hidden1.setMinWidth(0);
        hidden1.setPreferredWidth(0);
        hidden1.setMaxWidth(0);

        TableColumn hidden2 = jTableStudent.getColumnModel().getColumn(2);
        hidden2.setMinWidth(0);
        hidden2.setPreferredWidth(0);
        hidden2.setMaxWidth(0);
    }
    public void mouseClicked(MouseEvent e) {

        if (e.getSource() == jTableStudent) {
            if (e.getButton() == MouseEvent.BUTTON1) {
                if (e.getClickCount() == 2) {
                    int row = jTableStudent.getSelectedRow();
                    if (row != -1) {
                        Object id = jTableStudent.getValueAt(row, 0);
                        Object username = jTableStudent.getValueAt(row, 1);
                        Object password = jTableStudent.getValueAt(row, 2);
                        Object firstName = jTableStudent.getValueAt(row, 3);
                        Object lastName = jTableStudent.getValueAt(row, 4);
                        Object age = jTableStudent.getValueAt(row, 5);
                        Object gender = jTableStudent.getValueAt(row, 6);
                        Object address = jTableStudent.getValueAt(row, 7);
                        Object email = jTableStudent.getValueAt(row, 8);
                        Object mobile1 = jTableStudent.getValueAt(row, 9);
                        Object mobile2 = jTableStudent.getValueAt(row, 10);
                        //...Cast to String below
                        student.setId(Integer.parseInt(id.toString().trim()));
                        jTextFieldUsername.setText(username.toString());
                    jPasswordField1.setText(password.toString());
                        jTextFieldFirstname.setText(firstName.toString());
                        jTextFieldLastname.setText(lastName.toString());
                        jTextFieldAge.setText(age.toString());
                        //...Parse Gender to literal boolean
                        //  System.out.println(Boolean.parseBoolean(genderl.toString()));
                        if (Boolean.parseBoolean(gender.toString())) {
                            jRadioButtonMale.setSelected(true);
                            jRadioButtonFemale.setSelected(false);
                        } else if (Boolean.parseBoolean(gender.toString()) == false) {
                            jRadioButtonFemale.setSelected(true);
                            jRadioButtonMale.setSelected(false);
                        }
                        jTextFieldAddress.setText(address.toString());
                        jTextFieldEmail.setText(email.toString());
                        jTextFieldMobile.setText(mobile1.toString());
                       

                    }
                }
                }
        }
    }
    public void mousePressed(MouseEvent e) {

    }

    public void mouseReleased(MouseEvent e) {

    }

    public void mouseEntered(MouseEvent e) {

    }

    public void mouseExited(MouseEvent e) {

    }
}
